#:schema node_modules/wrangler/config-schema.json
name = "template"
main = "./platform/server.ts"
workers_dev = true

# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-11-11"

kv_namespaces = [{ binding = "cache", id = "your-actual-kv-namespace-id" }]

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
directory = "./build/client"

[build]
command = "bun run build"

[vars]
GITHUB_OWNER = "vhscom"
GITHUB_REPO = "remix-cloudflare-template"