name: CI

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: canary

      - name: Install dependencies
        run: bun install

      - name: Install Playwright Browsers
        run: bunx playwright install chromium

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome check
        run: biome check .

      - name: Run type check
        run: bun run typecheck

      - name: Run tests with coverage
        run: bun run test:coverage
        env:
          CI: true

      - name: Build
        run: bun run build